---
# LSWA project installation and configuration role

dependencies:

  # Role and usage dependencies
  - { role: svn }
  - { role: git }
  - { role: postgresql }

  # Usage dependencies

  - role: smartsvn

  - role: oraclejdk
    oraclejdk_version: 1.7.0_80
    oraclejdk_short_version: 7
    oraclejdk_url: http://jdk.phmd.net/jdk-7u80-linux-x64.tar.gz
    oraclejdk_config_workon: false
  
  - role: netbeans
    netbeans_version: 8.1

  - role: tomcat
    tomcat_version: 8.0.50
