---

- name: installation | install python dependencies
  become: true
  apt:
    pkg: "{{ item }}"
  with_items:
    - python-pip
    - python-dev
    - postgresql-server-dev-all

- name: installation | install pip dependencies
  become: true
  pip:
    name: pexpect
    version: 3.3

- name: installation | install pgadmin4
  become: true
  pip:
    name: "{{ pgadmin4_pip_download }}"

- name: installation | create local config
  become: true
  shell: cd {{ pgadmin4_python_dist_dir }}/pgadmin4 && cp config.py config_local.py

- name: installation | set desktop mode
  become: true
  lineinfile:
    dest: "{{ pgadmin4_python_dist_dir }}/pgadmin4/config_local.py"
    line: 'SERVER_MODE = False'

- name: installation | generate init.d script
  become: true
  template:
    src: ../templates/pgadmin4.j2
    dest: /etc/init.d/pgadmin4
    mode: 0755


- name: configuration | check .bashrc_common is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_common"
  register: bashrc_common

- name: configuration | generate alias in .bashrc_common
  when: bashrc_common.stat.exists
  lineinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_common"
    insertafter: "# @ALIASES"
    line: alias pgadmin='/etc/init.d/pgadmin4 start'
