---

- name: installation | download archive
  get_url:
    url: "{{ eclipse_url }}"
    dest: /tmp/eclipse.tar.gz

- name: installation | create parent directory
  become: true
  file:
    path: /opt/eclipse
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: installation | unarchive
  unarchive:
    src: /tmp/eclipse.tar.gz
    dest: /opt/eclipse

- name: installation | install in place
  shell: mv /opt/eclipse/eclipse/ /opt/eclipse/{{ eclipse_version }}

- name: installation | create menu
  become: true
  template:
    src: ../templates/eclipse.desktop.j2
    dest: /usr/share/applications/eclipse-{{ eclipse_version }}.desktop

- name: finalization | delete archive
  file:
    path: /tmp/eclipse.tar.gz
    state: absent
