---

- name: preparation | check if already installed
  stat:
    path: /opt/eclipse/{{ eclipse_version }}
  register: eclipse_installed

- import_tasks: installation.yml
  when: eclipse_installed.stat.isdir is not defined

- import_tasks: features.yml