---

- name: directories deletion
  become: true
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ dirs_to_delete }}"

- name: directories creation
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    recurse: true
  with_items: "{{ dirs_to_create }}"

- name: symlink creation
  become: true
  file:
    path: "{{ item.path }}"
    state: link
    src: "{{ item.src }}"
    force: true
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
  with_items: "{{ dirs_symlink }}"
