---

- name: directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic/spoutnik"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: clone
  git:
    repo: http://git.phmd.net/spoutnik/spoutnik-{{ item }}.git
    dest: "{{ workspace_dir }}/apologic/spoutnik/{{ item }}"
  with_items:
    - accueil
    - actualite
    - administration
    - cas
    - cas-utilisateur
    - configuration
    - docs
    - livrable
    - parc-applicatif
    - shared
    - synchro-lswa
    - tools


- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate spoutnik .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @WORKON_CASE"
    marker: "# {mark} ANSIBLE SPOUTNIK WORKON"
    block: |
      spoutnik|spk)
          cd "{{ workspace_dir }}/apologic/spoutnik"

          export JAVA_HOME="$ORIGINAL_JAVA_HOME"
          export GRADLE_HOME="$ORIGINAL_GRADLE_HOME"
          export PATH="$ORIGINAL_PATH"

          workon_log_title

          workon_log "Spoutnik"  
          pwd

          workon_log "GIT"
          git --version

          workon_log "JAVA"
          java -version

          workon_log "GRADLE" "$(gradle -version)"

          workon_log_end
          ;;
