---

- name: directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic/spoutnik"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: clone
  git:
    repo: http://git.phmd.net/spoutnik/spoutnik-{{ item }}.git
    dest: "{{ workspace_dir }}/apologic/spoutnik/{{ item }}"
  with_items:
    - accueil
    - actualite
    - administration
    - cas
    - cas-compte
    - configuration
    - docs
    - livrable
    - parc-applicatif
    - shared
    - synchro-lswa
    - tools

- name: installation | create databases
  when: spoutnik_create_db
  postgresql_db:
    name: "{{ item }}"
  with_items:
    - spoutnik_actualite
    - spoutnik_administration
    - spoutnik_cas_compte
    - spoutnik_configuration
    - spoutnik_livrable
    - spoutnik_parc_applicatif
    - spoutnik_synchro_lswa


- name: configuration | git author
  when: apologic_gitconfig_user_name is defined and apologic_gitconfig_user_email is defined
  blockinfile:
    dest: "{{ workspace_dir }}/apologic/spoutnik/{{ item }}/.git/config"
    insertbefore: BOF
    block: |
      [user]
          name = {{ apologic_gitconfig_user_name }}
          email = {{ apologic_gitconfig_user_email }}
  with_items:
    - accueil
    - actualite
    - administration
    - cas
    - cas-compte
    - configuration
    - docs
    - livrable
    - parc-applicatif
    - shared
    - synchro-lswa
    - tools

- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate spoutnik .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @WORKON_CASE"
    marker: "# {mark} ANSIBLE SPOUTNIK WORKON"
    block: |
      spoutnik|spk)
          cd "{{ workspace_dir }}/apologic/spoutnik"

          export JAVA_HOME="$ORIGINAL_JAVA_HOME"
          export GRADLE_HOME="$ORIGINAL_GRADLE_HOME"
          export PATH="$ORIGINAL_PATH"

          workon_log_title

          workon_log "Spoutnik"  
          pwd

          workon_log "GIT"
          git --version

          workon_log "JAVA"
          java -version

          workon_log "GRADLE" "$(gradle -version)"

          workon_log "NODEJS"
          node -v

          workon_log "NPM"
          npm -version

          workon_log_end
          ;;
