---
# Playbook for Apologic development machine


- include: development.yml

- name: Apologic development playbook
  hosts: apologic

  roles:

    # Java
    - { role: oraclejdk }

    # Private projects
    - { role: holborn }
    - { role: kilburn, when: kilburn }
    - { role: west-acton, when: west_acton }
    - { role: archived-projects, when: archived_projects }

    # Apologic projects
    - { role: lswa }
    - { role: costarica }
    - { role: spoutnik }
    - { role: poc-gestion-versions, when: poc_gestion_versions }
