---
# Playbook for Apologic development machine


- import_playbook: development.yml

- name: Apologic development playbook
  hosts: apologic

  roles:

    # Java

    - { role: oraclejdk }

    - role: oraclejdk
      oraclejdk_version: 9
      oraclejdk_short_version: 9
      oraclejdk_url: http://download.oracle.com/otn-pub/java/jdk/9+181/jdk-9_linux-x64_bin.tar.gz
      oraclejdk_zipdir: jdk-9
      oraclejdk_config_workon: false

    # Private projects
    - { role: holborn }
    - { role: kilburn, when: kilburn }
    - { role: west-acton, when: west_acton }
    - { role: archived-projects, when: archived_projects }

    # Apologic projects
    - { role: lswa }
    - { role: costarica }
    - { role: spoutnik }
    - { role: poc-gestion-versions, when: poc_gestion_versions }

  tasks:

    - name: update alternatives java
      become: true
      shell: update-alternatives --auto java
