---
# Playbook for development machine


- name: Development playbook
  hosts: development

  roles:

    # General
    - role: vbox
    - role: dirs

    # Terminal
    - role: tilix
    - role: nass600.powerline
    - role: powerline
    - role: vim
    - role: bash

    # Chrome
    - role: cmprescott.chrome
      become: true

    # Text Editors

    - role: vaulttec.sublimetext
    - role: theNewFlesh.sublime-config

    - role: gantsign.atom
      users:
        - username: "{{ ansible_user }}"
          atom_packages:
            - file-icons
            - autosave-onchange
            - highlight-selected
            - minimap
            - minimap-highlight-selected
            - markdown-preview-enhanced
            - language-gradle
            - language-groovy
            - language-sql
          atom_config_overwrite: true
          atom_config:
            "*":
              core:
                projectHome: "{{ workspace_dir }}"
                packagesWithKeymapsDisabled:
                  - markdown-preview
                telemetryConsent: "limited"
              editor:
                fontSize: 12
              welcome:
                showOnStartup: false
              minimap:
                plugins:
                  "highlight-selected": true
                  "highlight-selectedDecorationsZIndex": 0
              "tree-view":
                squashDirectoryNames: true
              whitespace:
                ensureSingleTrailingNewline: false
                removeTrailingWhitespace: false

    # SCM
    - role: git
    - role: kdiff3

    # Database
    - role: postgresql
    - role: pgadmin4

    # Java
    - role: gradle
    - role: intellij
    - role: jdgui
