---
# Playbook for development machine


- name: Development playbook
  hosts: development

  roles:

    # General
    - { role: vbox }
    - { role: dirs }

    # Terminal
    - { role: tilix }
    - { role: nass600.powerline }
    - { role: powerline }
    - { role: vim }
    - { role: bash }

    # Chrome
    - { role: cmprescott.chrome, become: true }

    # Sublime Text
    - { role: vaulttec.sublimetext }
    - { role: theNewFlesh.sublime-config }

    # SCM
    - { role: git }
    - { role: kdiff3 }

    # Database
    - { role: postgresql }
    - { role: pgadmin4 }

    # Java
    - { role: gradle }
    - { role: intellij }
    - { role: jdgui }
