---
# Playbook for home development machine


- name: Home development playbook
  hosts: home

  roles:

    # Chrome
    - { role: cmprescott.chrome, become: true }

    # Git
    - git
    - kdiff3

    # Terminal
    - nass600.powerline
    - powerline-config
    - tilix

    # Sublime Text
    - vaulttec.sublimetext
    - theNewFlesh.sublime-config

    # Java
    - openjdk
    - eclipse
