---
# Playbook for home development machine


- name: Home development playbook
  hosts: home

  roles:

    # Directories
    - { role: dirs }

    # Terminal
    - { role: tilix }
    - { role: nass600.powerline }
    - { role: powerline }
    - { role: bash }

    # Chrome
    - { role: cmprescott.chrome, become: true }

    # Sublime Text
    - { role: vaulttec.sublimetext }
    - { role: theNewFlesh.sublime-config }

    # SCM
    - { role: git }
    - { role: kdiff3 }

    # Database
    - { role: postgresql }
    - { role: pgadmin4 }

    # Java
    - { role: openjdk }
    - { role: eclipse }
    - { role: gradle }

    # Private projects
    - { role: holborn }
    - { role: kilburn }
    - { role: archived-projects, when: archived_projects }

    # Apologic projects
    - { role: lswa, when: lswa }
    - { role: spoutnik, when: spoutnik }
    - { role: costarica, when: costarica }
    - { role: poc-gestion-versions, when: poc_gestion_versions }
