---
# Playbook for home development machine


- name: Home development playbook
  hosts: home

  roles:

    # Git
    - gitconfig

    # Terminal
    - nass600.powerline
    - tilix

    # Sublime Text
    - vaulttec.sublimetext
    - theNewFlesh.sublime-config
