---
# Playbook for home development machine


- import_playbook: development.yml

- name: Home development playbook
  hosts: home

  roles:

    # Java
    - { role: openjdk }

    # Private projects
    - { role: holborn }
    - { role: kilburn }
    - { role: west-acton }
    - { role: archived-projects, when: archived_projects }

    # Apologic projects
    - { role: lswa, when: lswa }
    - { role: costarica, when: costarica }
    - { role: spoutnik, when: spoutnik }
    - { role: poc-gestion-versions, when: poc_gestion_versions }
