---

- name: installation | download archive
  get_url:
    url: https://services.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip
    dest: /tmp/gradle.zip

- name: installation | create parent directory
  become: true
  file:
    path: /opt/gradle
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: installation | unarchive
  unarchive:
    src: /tmp/gradle.zip
    dest: /opt/gradle

- name: installation | install in place
  shell: mv /opt/gradle/gradle-{{ gradle_version }}/ /opt/gradle/{{ gradle_version }}

- name: finalization | delete archive
  file:
    path: /tmp/gradle.zip
    state: absent
