---

- name: installation | download archive
  get_url:
    url: https://services.gradle.org/distributions/gradle-{{ gradle_version }}-bin.zip
    dest: /tmp/gradle.zip

- name: installation | create parent directory
  become: true
  file:
    path: /opt/gradle
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: installation | unarchive
  unarchive:
    src: /tmp/gradle.zip
    dest: /opt/gradle

- name: installation | install in place
  shell: mv /opt/gradle/gradle-{{ gradle_version }}/ /opt/gradle/{{ gradle_version }}

- name: finalization | delete archive
  file:
    path: /tmp/gradle.zip
    state: absent


- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate env vars in .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @PATHOME"
    marker: "# {mark} ANSIBLE GRADLE WORKON"
    block: |
      export GRADLE_HOME="/opt/gradle/{{ gradle_version }}"
      export ORIGINAL_GRADLE_HOME="$GRADLE_HOME"
      export PATH="$GRADLE_HOME/bin:$PATH"
