---

- name: preparation | check if already installed
  stat:
    path: /opt/gradle/{{ gradle_version }}
  register: gradle_installed

- import_tasks: installation.yml
  when: gradle_installed.stat.isdir is not defined

- import_tasks: configuration.yml
