---

- name: preparation | check if already installed
  stat:
    path: /opt/gradle/{{ gradle_version }}
  register: gradle_installed

- include: installation.yml
  when: gradle_installed.stat.isdir is not defined
