---

- name: preparation | check if already installed
  stat:
    path: /opt/jdk/{{ oraclejdk_version }}
  register: oraclejdk_installed

- include: installation.yml
  when: oraclejdk_installed.stat.isdir is not defined

- include: configuration.yml
