---

- name: preparation | check if already installed
  stat:
    path: /opt/jdk/{{ oraclejdk_version }}
  register: oraclejdk_installed

- import_tasks: installation.yml
  when: oraclejdk_installed.stat.isdir is not defined

- import_tasks: configuration.yml
