---

- name: installation | update cache
  become: true
  apt:
    update_cache: yes

- name: installation | install
  become: true
  apt:
    name: openjdk-{{ openjdk_version }}-jdk
    state: latest


- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate env vars in .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @PATHOME"
    marker: "# {mark} ANSIBLE OPENJDK WORKON"
    block: |
      export JAVA_HOME="/usr/lib/jvm/java-{{ openjdk_version }}-openjdk-amd64"
      export ORIGINAL_JAVA_HOME="$JAVA_HOME"
      export PATH="$JAVA_HOME/bin:$PATH"