---

archived_projects_list:
  - bakerloo
  - bakerstreet
  - ducktales
  - lab-angular-extensible
  - lab-atlassian-plugin-framework
  - lab-classloader
  - lab-javafx
  - lab-spring-extensible
  - lab-static-extensible
  - tools-docker
  - tools-linux
