---

- name: preparation | check if already installed
  stat:
    path: /opt/jdgui/jd-gui-{{ jdgui_version }}.jar
  register: jdgui_installed

- include: installation.yml
  when: jdgui_installed.stat.exists == false

- include: configuration.yml
