---

- name: directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: true

- name: checkout
  environment:
    - LC_ALL: en_US.UTF-8
    - LC_CTYPE: en_US.UTF-8
  subversion:
    repo: http://81.255.60.234/usvn/svn/costarica/trunk
    dest: "{{ workspace_dir }}/apologic/costarica"
    username: "{{ apologic_svn_login }}"
    password: "{{ apologic_svn_password }}"
