---

- name: installation | directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic/costarica"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: installation | clone
  git:
    repo: http://git.phmd.net/{{ item.path }}.git
    dest: "{{ workspace_dir }}/apologic/costarica/{{ item.name }}"
  with_items: "{{ costarica_repo }}"

- name: installation | create database
  when: costarica_create_db
  postgresql_db:
    name: costarica_portail


- name: configuration | git author
  when: apologic_gitconfig_user_name is defined and apologic_gitconfig_user_email is defined
  blockinfile:
    dest: "{{ workspace_dir }}/apologic/costarica/{{ item.name }}/.git/config"
    insertbefore: BOF
    block: |
      [user]
          name = {{ apologic_gitconfig_user_name }}
          email = {{ apologic_gitconfig_user_email }}
  with_items: "{{ costarica_repo }}"

- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate costarica .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @WORKON_CASE"
    marker: "# {mark} ANSIBLE COSTARICA WORKON"
    block: |
      costarica|cri)
          cd "{{ workspace_dir }}/apologic/costarica"

          export JAVA_HOME="$ORIGINAL_JAVA_HOME"
          export GRADLE_HOME="$ORIGINAL_GRADLE_HOME"
          export PATH="$ORIGINAL_PATH"

          workon_log_title

          workon_log "Costarica"  
          pwd

          workon_log "GIT"
          git --version

          workon_log "JAVA"
          java -version

          workon_log "GRADLE" "$(gradle -version)"

          workon_log_end
          ;;
