---

- name: preparation | check if already installed
  stat:
    path: /opt/nodejs/{{ nodejs_version }}
  register: nodejs_installed

- import_tasks: installation.yml
  when: nodejs_installed.stat.isdir is not defined

- import_tasks: configuration.yml
