---

- name: installation | directory
  become: true
  file:
    path: "{{ workspace_dir }}/private"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: installation | clone
  git:
    repo: git@gitlab.com:SebastienM4j/kilburn.git
    dest: "{{ workspace_dir }}/private/kilburn"

- name: installation | create databases
  postgresql_db:
    name: "{{ item }}"
  with_items:
    - kilburn
    - kilburn_dev


- name: configuration | git author
  when: home_gitconfig_user_name is defined and home_gitconfig_user_email is defined
  blockinfile:
    dest: "{{ workspace_dir }}/private/kilburn/.git/config"
    insertbefore: BOF
    block: |
      [user]
          name = {{ home_gitconfig_user_name }}
          email = {{ home_gitconfig_user_email }}
          
- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate kilburn .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @WORKON_CASE"
    marker: "# {mark} ANSIBLE KILBURN WORKON"
    block: |
      kilburn|klb)
          cd "{{ workspace_dir }}/private/kilburn"

          export JAVA_HOME="$ORIGINAL_JAVA_HOME"
          export GRADLE_HOME="$ORIGINAL_GRADLE_HOME"
          export PATH="$ORIGINAL_PATH"

          workon_log_title

          workon_log "Kilburn"  
          pwd

          workon_log "GIT"
          git --version

          workon_log "JAVA"
          java -version

          workon_log "GRADLE" "$(gradle -version)"

          workon_log_end
          ;;
