---

- name: preparation | check if already installed
  stat:
    path: /opt/maven/{{ maven_version }}
  register: maven_installed

- import_tasks: installation.yml
  when: maven_installed.stat.isdir is not defined

- import_tasks: configuration.yml
