---

- name: preparation | check if already installed
  stat:
    path: /opt/intellij/{{ intellij_version }}
  register: intellij_installed

- include: installation.yml
  when: intellij_installed.stat.isdir is not defined
