---

- name: preparation | check if already installed
  stat:
    path: /opt/smartsvn/{{ smartsvn_version }}
  register: smartsvn_installed

- include: installation.yml
  when: smartsvn_installed.stat.isdir is not defined
