---

- name: directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic/poc-gestion-versions"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: true

- name: clone
  git:
    repo: http://git.phmd.net/poc-gestion-versions/{{ item }}.git
    dest: "{{ workspace_dir }}/apologic/poc-gestion-versions/{{ item }}"
  with_items:
    - docker
    - git
