---

- name: installation | add repository
  become: true
  apt_repository:
    repo: ppa:webupd8team/terminix

- name: installation | update cache
  become: true
  apt:
    update_cache: yes

- name: installation | install
  apt:
    name: tilix
    state: latest

- name: configuration | dconf installation
  apt:
      name: dconf-cli

- name: configuration | generation configuration file
  template:
    src: ../templates/tilix.dconf.j2
    dest: "{{ ansible_user_dir }}/.tilix.dconf"

- name: configuration | load configuration
  shell: dconf load /com/gexperts/Tilix/ < {{ ansible_user_dir }}/.tilix.dconf