---

- name: directory
  become: true
  file:
    path: "{{ workspace_dir }}/private"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: clone
  git:
    repo: git@gitlab.com:SebastienM4j/sebastienm4j.github.io.git
    dest: "{{ workspace_dir }}/private/sebastienm4j-github-io"
    update: false


- name: configuration | git author
  when: home_gitconfig_user_name is defined and home_gitconfig_user_email is defined
  blockinfile:
    dest: "{{ workspace_dir }}/private/sebastienm4j-github-io/.git/config"
    insertbefore: BOF
    block: |
      [user]
          name = {{ home_gitconfig_user_name }}
          email = {{ home_gitconfig_user_email }}

- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate sebastienm4j-github-io .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @WORKON_CASE"
    marker: "# {mark} ANSIBLE SEBASTIENM4J-GITHUB-IO WORKON"
    block: |
      gio)
          cd "{{ workspace_dir }}/private/sebastienm4j-github-io"

          export JAVA_HOME="$ORIGINAL_JAVA_HOME"
          export GRADLE_HOME="$ORIGINAL_GRADLE_HOME"
          export PATH="$ORIGINAL_PATH"

          workon_log_title

          workon_log "sebastienm4j-github-io"  
          pwd

          workon_log "GIT"
          git --version
          
          workon_log "NODEJS"
          node -v

          workon_log "NPM"
          npm -version

          workon_log_end
          ;;
