---

- name: installation | directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic/lswa"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true

- name: installation | checkout lswa
  environment:
    - LC_ALL: en_US.UTF-8
    - LC_CTYPE: en_US.UTF-8
  subversion:
    repo: http://81.255.60.234/usvn/svn/lab4/{{ item.branch }}
    dest: "{{ workspace_dir }}/apologic/lswa/{{ item.name }}"
    username: "{{ apologic_svn_login }}"
    password: "{{ apologic_svn_password }}"
  with_items: "{{ lswa_repo }}"

- name: installation | create database
  when: lswa_create_db
  postgresql_db:
    name: lswa_{{ item.name }}
  with_items: "{{ lswa_repo }}"

- name: installation | create database tu
  when: lswa_create_db
  postgresql_db:
    name: lswa_{{ item.name }}_tu
  with_items: "{{ lswa_repo }}"

- name: installation | clone lswa/launcher
  git:
    repo: http://git.phmd.net/lswa/launcher.git
    dest: "{{ workspace_dir }}/apologic/lswa/launcher"


- name: configuration | check .bashrc_workon is present
  stat:
    path: "{{ ansible_user_dir }}/.bashrc_workon"
  register: bashrc_workon

- name: configuration | generate lswa .bashrc_workon
  when: bashrc_workon.stat.exists
  blockinfile:
    dest: "{{ ansible_user_dir }}/.bashrc_workon"
    insertafter: "# @WORKON_CASE"
    marker: "# {mark} ANSIBLE LSWA WORKON"
    block: |
      apoweb|lswa)
          cd "{{ workspace_dir }}/apologic/lswa"

          # TODO install JDK 7
          export JAVA_HOME="$ORIGINAL_JAVA_HOME"
          export GRADLE_HOME="$ORIGINAL_GRADLE_HOME"
          export ANT_HOME="/opt/netbeans/{{ netbeans_version }}/extide/ant"
          export PATH="$ANT_HOME/bin:$ORIGINAL_PATH"

          workon_log_title

          workon_log "LSWA"  
          pwd

          workon_log "SVN"
          svn --version --quiet

          workon_log "GIT"
          git --version

          workon_log "JAVA"
          java -version

          workon_log "GRADLE" "$(gradle -version)"

          workon_log "ANT"
          ant -version

          workon_log_end
          ;;
