---

- name: directory
  become: true
  file:
    path: "{{ workspace_dir }}/apologic/lswa"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"
    recurse: true

- name: checkout | lswa
  environment:
    - LC_ALL: en_US.UTF-8
    - LC_CTYPE: en_US.UTF-8
  subversion:
    repo: http://81.255.60.234/usvn/svn/lab4/trunk
    dest: "{{ workspace_dir }}/apologic/lswa/lswa"
    username: "{{ apologic_svn_login }}"
    password: "{{ apologic_svn_password }}"

- name: clone | lswa/launcher
  git:
    repo: http://git.phmd.net/lswa/launcher.git
    dest: "{{ workspace_dir }}/apologic/lswa/launcher"
